[package]
name = "splaycompress"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"], optional = true }

[features]
binary = ["clap"]

[[bin]]
name = "jan"
required-features = ["binary"]
path = "src/bin/jan.rs"
